apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  labels:
    app: mssql
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433          # porta que o service expõe dentro do cluster
      targetPort: 1433    # porta que o container do banco está ouvindo