apiVersion: v1
kind: Service
metadata:
  name: persistencia-metrics-service
spec:
  selector:
    app: persistencia
  ports:
    - protocol: TCP
      port: 9090       # porta do serviço que o cluster vai usar
      targetPort: 9090 # porta no pod que está ouvindo
