apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000           # Porta interna do Grafana
      targetPort: 3000     # Porta do container
      nodePort: 32000      
