apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'cadastro_service'
        static_configs:
          - targets: ['cadastro-metrics-service:8080']

      - job_name: 'persistencia_service'
        static_configs:
          - targets: ['persistencia-metrics-service:9090']
