apiVersion: v1
kind: Service
metadata:
  name: cadastro-service
spec:
  type: NodePort
  selector:
    app: cadastro
  ports:
    - protocol: TCP
      port: 80          # porta do Service (para acesso interno no cluster)
      targetPort: 8080  # porta do container
      nodePort: 30080   # mesma porta que você usava antes
