apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastro-deployment
  labels:
    app: cadastro
    tier: backend
    version: v1
  annotations:
    maintainer: "debora.krikowski@fiap.com.br"
    description: "Deployment do serviço de Cadastro que registra usuários e envia dados para o serviço de Persistência"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cadastro
  template:
    metadata:
      labels:
        app: cadastro
        tier: backend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: cadastro
        image: cadastro-service:v2
        imagePullPolicy: Never 
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        envFrom:
        - configMapRef:
            name: cadastro-config
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: PERSISTENCIA_SERVICE_BASEURL
          value: "http://persistencia-service"
        # Variáveis para RabbitMQ
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_USERNAME
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
