apiVersion: v1
kind: Service
metadata:
  name: cadastro-service
spec:
  type: NodePort
  selector:
    app: cadastro
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 8080  
      nodePort: 30080   
