name: Deploy Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Decode and configure Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          mkdir -p ~/.kube
          mv kubeconfig ~/.kube/config

      - name: Apply SQL Server configs
        run: |
          kubectl apply -f k8s/SQLServer/mssql-secret.yaml
          kubectl apply -f k8s/SQLServer/mssql-pvc.yaml
          kubectl apply -f k8s/SQLServer/mssql-deployment.yaml
          kubectl apply -f k8s/SQLServer/mssql-service.yaml
          kubectl apply -f k8s/SQLServer/mssql-sqlclient.yaml

      - name: Apply CadastroService configs
        run: |
          kubectl apply -f k8s/CadastroService/cadastro-configmap.yaml
          kubectl apply -f k8s/CadastroService/cadastro-service.yaml
          kubectl apply -f k8s/CadastroService/cadastro-deployment.yaml

      - name: Apply PersistenciaService configs
        run: |
          kubectl apply -f k8s/PersistenciaService/persistencia-configmap.yaml
          kubectl apply -f k8s/PersistenciaService/persistencia-service.yaml
          kubectl apply -f k8s/PersistenciaService/persistencia-deployment.yaml

      - name: Verify all resources
        run: |
          kubectl get pods
          kubectl get services
