name: E2E Tests - Microservices Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: "YourStrong!Passw0rd"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies - PersistenciaService
      run: dotnet restore PersistenciaService/PersistenciaService.csproj

    - name: Restore dependencies - CadastroService
      run: dotnet restore CadastroService/CadastroService.csproj

    - name: Build - PersistenciaService
      run: dotnet build PersistenciaService/PersistenciaService.csproj --configuration Release

    - name: Build - CadastroService
      run: dotnet build CadastroService/CadastroService.csproj --configuration Release

    - name: Run PersistenciaService API
      run: dotnet run --project PersistenciaService/PersistenciaService.csproj &
      env:
        ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=PersistenciaDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"

    - name: Wait for PersistenciaService to start
      run: sleep 15

    - name: Run CadastroService API
      run: dotnet run --project CadastroService/CadastroService.csproj &
      env:
        PERSISTENCIASERVICE__BASEURL: "http://localhost:5006"

    - name: Wait for CadastroService to start
      run: sleep 15

    - name: Run integration tests (End-to-End)
      run: dotnet test CadastroService/CadastroService.IntegrationTests/CadastroService.IntegrationTests.csproj --no-build --verbosity normal

    - name: Stop APIs
      run: |
        pkill -f PersistenciaService
        pkill -f CadastroService
