name: CI - PersistenciaService

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Restore para ambos os projetos
    - name: Restore dependencies
      run: dotnet restore PersistenciaService.sln

    # Formatação só no projeto PersistenciaService
    - name: Run code format check
      run: dotnet format --verify-no-changes PersistenciaService/PersistenciaService.csproj
      continue-on-error: true

    # Build da solução para garantir testes compilados
    - name: Build solution
      run: dotnet build PersistenciaService.sln --configuration Release --no-restore

    # Executa os testes (sem --no-build para compilar testes se necessário)
    - name: Run tests
      run: dotnet test PersistenciaService.Tests/PersistenciaService.Tests.csproj --verbosity normal

    - name: Prepare upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: noop
        path: noop
      continue-on-error: true

    - name: Publish build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: persistencia-service-build
        path: PersistenciaService/bin/Release/
