name: CI - PersistenciaService

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore PersistenciaService/PersistenciaService.csproj

    - name: Run code format check
      run: dotnet format --verify-no-changes PersistenciaService/PersistenciaService.csproj
      continue-on-error: true

    - name: Build project
      run: dotnet build PersistenciaService/PersistenciaService.csproj --no-restore --configuration Release

    - name: Run tests
      run: dotnet test PersistenciaService/PersistenciaService.Tests/PersistenciaService.Tests.csproj --no-build --verbosity normal

    - name: Publish build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: persistencia-service-build
        path: PersistenciaService/bin/Release/
        
    # Optional: build docker image
    - name: Build Docker image
      if: github.event_name != 'pull_request'
      run: |
        docker build -t persistenciaservice:latest PersistenciaService/
